version: "3.9"
volumes:
  db-volume-gcs:
  redis-cache:
services:
  web:
    links:
      - database:localhost
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - env=local
    volumes:
      - .:/var/www/html
      - ~/.composer:/home/php/.composer:rw
    ports:
      - ${WEB_PORT}:80
    environment:
      ENV: local
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      COMPOSER_MEMORY_LIMIT: -1
    restart: always
  database:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - ${DATABASE_PORT}:3306
    command:
      - --max_allowed_packet=32505856
      - --disable-log-bin
      - --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db-volume-gcs:/var/lib/mysql:delegated
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - database:database
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=database
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASS}
  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    volumes:
      - redis-cache:/data:delegated